# docker 컨테이너 버전을 명시
version: '3'

# services는 컨테이너
services:
  react-app:
    # -it 옵션을 위해 사용됨 (표준입출력)
    stdin_open: true
    tty: true
    # 현재 경로에 이미지 빌드
    build: .
    # 포트 포워딩
    ports:
      - '8080:3000'
    # 호스트 디렉토리에 바인드 마운트
    volumes:
      - ./src:/app/src:ro
    # 환경 변수 설정 - opt.1(하드코딩)
    environment:
      - REACT_APP_NAME=leanmath
      - REACT_APP_TITLE=LeanERP
    # 환경 변수 설정 - opt.2(.env)
    env_file:
      - ./.env
